// RacTerm — Terminal Emulator Core (TERMINAL_PROTOCOLS.md)
//
// Ties together: EscParser → Action → ScreenBuffer + Cursor.
// This is the main entry point for processing PTY output.

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

use crate::buffer::{Cell, CellAttrs, Color, ScreenBuffer};
use crate::cursor::Cursor;
use crate::escape::{Action, EscParser};

/// The terminal emulator.
pub struct Terminal {
    pub buffer: ScreenBuffer,
    pub cursor: Cursor,
    parser: EscParser,
    /// Current text attributes for new characters.
    fg: Color,
    bg: Color,
    attrs: CellAttrs,
    /// Window title (set via OSC).
    pub title: String,
    /// Response bytes to send back to the master (DSR, DA, etc.).
    response_buf: Vec<u8>,
}

impl Terminal {
    pub fn new(rows: usize, cols: usize) -> Self {
        Terminal {
            buffer: ScreenBuffer::new(rows, cols),
            cursor: Cursor::new(rows, cols),
            parser: EscParser::new(),
            fg: Color::Default,
            bg: Color::Default,
            attrs: CellAttrs::default(),
            title: String::new(),
            response_buf: Vec::new(),
        }
    }

    /// Drain any response bytes generated by DSR/DA queries.
    /// The caller should write these back to the PTY master.
    pub fn drain_response(&mut self) -> Vec<u8> {
        core::mem::take(&mut self.response_buf)
    }

    /// Process output bytes from the shell/PTY.
    pub fn feed(&mut self, data: &[u8]) {
        for &byte in data {
            if let Some(action) = self.parser.feed(byte) {
                self.execute_action(action);
            }
        }
    }

    /// Resize the terminal.
    pub fn resize(&mut self, rows: usize, cols: usize) {
        self.buffer.resize(rows, cols);
        self.cursor.resize(rows, cols);
    }

    fn execute_action(&mut self, action: Action) {
        match action {
            Action::Print(ch) => self.print(ch),
            Action::Execute(byte) => self.execute_control(byte),
            Action::CsiDispatch { params, intermediates: _, final_byte, private } => {
                self.execute_csi(&params, final_byte, private);
            }
            Action::OscDispatch(s) => self.execute_osc(&s),
            Action::EscDispatch(byte) => self.execute_esc(byte),
        }
    }

    fn print(&mut self, ch: char) {
        // Handle wrap pending
        if self.cursor.wrap_pending {
            let needs_scroll = self.cursor.do_wrap();
            if needs_scroll {
                self.buffer.scroll_up(1, self.cursor.scroll_top, self.cursor.scroll_bottom);
            }
        }

        self.buffer.put_char(
            self.cursor.row,
            self.cursor.col,
            ch,
            self.fg,
            self.bg,
            self.attrs,
        );

        self.cursor.advance_after_print();
    }

    fn execute_control(&mut self, byte: u8) {
        match byte {
            0x07 => {} // BEL — could trigger visual bell
            0x08 => self.cursor.backspace(),
            0x09 => self.cursor.tab(),
            0x0A | 0x0B | 0x0C => {
                // LF, VT, FF — all treated as line feed
                let needs_scroll = self.cursor.line_feed();
                if needs_scroll {
                    self.buffer.scroll_up(1, self.cursor.scroll_top, self.cursor.scroll_bottom);
                }
            }
            0x0D => self.cursor.carriage_return(),
            _ => {} // Ignore other C0 controls
        }
    }

    fn execute_csi(&mut self, params: &[u16], final_byte: u8, private: bool) {
        if private {
            self.execute_csi_private(params, final_byte);
            return;
        }

        let p1 = params.first().copied().unwrap_or(0);
        let p2 = params.get(1).copied().unwrap_or(0);

        match final_byte {
            // CUU — Cursor Up
            b'A' => self.cursor.move_up(p1.max(1) as usize),
            // CUD — Cursor Down
            b'B' => self.cursor.move_down(p1.max(1) as usize),
            // CUF — Cursor Forward
            b'C' => self.cursor.move_forward(p1.max(1) as usize),
            // CUB — Cursor Back
            b'D' => self.cursor.move_back(p1.max(1) as usize),
            // CUP — Cursor Position
            b'H' | b'f' => {
                let row = p1.max(1) as usize;
                let col = p2.max(1) as usize;
                self.cursor.set_position(row, col);
            }
            // ED — Erase Display
            b'J' => {
                match p1 {
                    0 => self.buffer.clear_below(self.cursor.row, self.cursor.col),
                    1 => self.buffer.clear_above(self.cursor.row, self.cursor.col),
                    2 | 3 => self.buffer.clear(),
                    _ => {}
                }
            }
            // EL — Erase Line
            b'K' => {
                match p1 {
                    0 => self.buffer.clear_line(self.cursor.row, self.cursor.col, self.buffer.cols),
                    1 => self.buffer.clear_line(self.cursor.row, 0, self.cursor.col + 1),
                    2 => self.buffer.clear_line(self.cursor.row, 0, self.buffer.cols),
                    _ => {}
                }
            }
            // IL — Insert Lines
            b'L' => {
                self.buffer.insert_lines(self.cursor.row, p1.max(1) as usize, self.cursor.scroll_bottom);
            }
            // DL — Delete Lines
            b'M' => {
                self.buffer.delete_lines(self.cursor.row, p1.max(1) as usize, self.cursor.scroll_bottom);
            }
            // SU — Scroll Up
            b'S' => {
                self.buffer.scroll_up(p1.max(1) as usize, self.cursor.scroll_top, self.cursor.scroll_bottom);
            }
            // SD — Scroll Down
            b'T' => {
                self.buffer.scroll_down(p1.max(1) as usize, self.cursor.scroll_top, self.cursor.scroll_bottom);
            }
            // SGR — Select Graphic Rendition
            b'm' => self.execute_sgr(params),
            // DSR — Device Status Report
            b'n' => {
                match p1 {
                    6 => {
                        // CPR: report cursor position as ESC[row;colR (1-based)
                        self.write_response_cpr(self.cursor.row + 1, self.cursor.col + 1);
                    }
                    5 => {
                        // Status report: terminal OK
                        self.response_buf.extend_from_slice(b"\x1b[0n");
                    }
                    _ => {}
                }
            }
            // DA — Device Attributes
            b'c' => {
                if p1 == 0 {
                    // Primary DA: report VT100-compatible terminal
                    self.response_buf.extend_from_slice(b"\x1b[?1;2c");
                }
            }
            // ICH — Insert Characters
            b'@' => {
                let n = p1.max(1) as usize;
                self.buffer.insert_chars(self.cursor.row, self.cursor.col, n);
            }
            // DCH — Delete Characters
            b'P' => {
                let n = p1.max(1) as usize;
                self.buffer.delete_chars(self.cursor.row, self.cursor.col, n);
            }
            // ECH — Erase Characters
            b'X' => {
                let n = p1.max(1) as usize;
                self.buffer.erase_chars(self.cursor.row, self.cursor.col, n);
            }
            // SCP — Save Cursor Position
            b's' => self.cursor.save(),
            // RCP — Restore Cursor Position
            b'u' => self.cursor.restore(),
            // DECSTBM — Set Scroll Region
            b'r' => {
                let top = p1.max(1) as usize;
                let bottom = if p2 == 0 { self.buffer.rows } else { p2 as usize };
                self.cursor.set_scroll_region(top, bottom);
            }
            _ => {} // Unrecognized — ignore
        }
    }

    fn execute_csi_private(&mut self, params: &[u16], final_byte: u8) {
        let p1 = params.first().copied().unwrap_or(0);

        match (p1, final_byte) {
            // DECTCEM — Show cursor
            (25, b'h') => self.cursor.visible = true,
            // DECTCEM — Hide cursor
            (25, b'l') => self.cursor.visible = false,
            // Alternate screen buffer enable
            (1049, b'h') => {
                self.cursor.save();
                self.buffer.enable_alternate();
            }
            // Alternate screen buffer disable
            (1049, b'l') => {
                self.buffer.disable_alternate();
                self.cursor.restore();
            }
            _ => {}
        }
    }

    fn execute_sgr(&mut self, params: &[u16]) {
        if params.is_empty() {
            self.reset_attrs();
            return;
        }

        let mut i = 0;
        while i < params.len() {
            match params[i] {
                0 => self.reset_attrs(),
                1 => self.attrs.bold = true,
                3 => self.attrs.italic = true,
                4 => self.attrs.underline = true,
                5 => self.attrs.blink = true,
                7 => self.attrs.reverse = true,
                9 => self.attrs.strikethrough = true,
                22 => self.attrs.bold = false,
                23 => self.attrs.italic = false,
                24 => self.attrs.underline = false,
                25 => self.attrs.blink = false,
                27 => self.attrs.reverse = false,
                29 => self.attrs.strikethrough = false,
                // Standard foreground colors
                30..=37 => self.fg = Color::Indexed((params[i] - 30) as u8),
                // Extended foreground: 38;5;n or 38;2;r;g;b
                38 => {
                    i += 1;
                    if i < params.len() {
                        match params[i] {
                            5 => {
                                i += 1;
                                if i < params.len() {
                                    self.fg = Color::Indexed(params[i] as u8);
                                }
                            }
                            2 => {
                                if i + 3 < params.len() {
                                    self.fg = Color::Rgb(
                                        params[i + 1] as u8,
                                        params[i + 2] as u8,
                                        params[i + 3] as u8,
                                    );
                                    i += 3;
                                }
                            }
                            _ => {}
                        }
                    }
                }
                39 => self.fg = Color::Default,
                // Standard background colors
                40..=47 => self.bg = Color::Indexed((params[i] - 40) as u8),
                // Extended background: 48;5;n or 48;2;r;g;b
                48 => {
                    i += 1;
                    if i < params.len() {
                        match params[i] {
                            5 => {
                                i += 1;
                                if i < params.len() {
                                    self.bg = Color::Indexed(params[i] as u8);
                                }
                            }
                            2 => {
                                if i + 3 < params.len() {
                                    self.bg = Color::Rgb(
                                        params[i + 1] as u8,
                                        params[i + 2] as u8,
                                        params[i + 3] as u8,
                                    );
                                    i += 3;
                                }
                            }
                            _ => {}
                        }
                    }
                }
                49 => self.bg = Color::Default,
                // Bright foreground
                90..=97 => self.fg = Color::Indexed((params[i] - 90 + 8) as u8),
                // Bright background
                100..=107 => self.bg = Color::Indexed((params[i] - 100 + 8) as u8),
                _ => {}
            }
            i += 1;
        }
    }

    fn execute_osc(&mut self, s: &str) {
        // OSC 0;title — set window title
        if let Some(title) = s.strip_prefix("0;") {
            self.title = String::from(title);
        }
    }

    fn execute_esc(&mut self, byte: u8) {
        match byte {
            // RIS — Full Reset
            b'c' => {
                self.buffer.clear();
                self.cursor = Cursor::new(self.buffer.rows, self.buffer.cols);
                self.reset_attrs();
                self.title = String::new();
            }
            // DECSC — Save cursor + attributes
            b'7' => self.cursor.save(),
            // DECRC — Restore cursor + attributes
            b'8' => self.cursor.restore(),
            // IND — Index (LF, scroll at bottom)
            b'D' => {
                let needs_scroll = self.cursor.line_feed();
                if needs_scroll {
                    self.buffer.scroll_up(1, self.cursor.scroll_top, self.cursor.scroll_bottom);
                }
            }
            // NEL — Next Line (CR + LF)
            b'E' => {
                self.cursor.carriage_return();
                let needs_scroll = self.cursor.line_feed();
                if needs_scroll {
                    self.buffer.scroll_up(1, self.cursor.scroll_top, self.cursor.scroll_bottom);
                }
            }
            // RI — Reverse Index
            b'M' => {
                let needs_scroll = self.cursor.reverse_index();
                if needs_scroll {
                    self.buffer.scroll_down(1, self.cursor.scroll_top, self.cursor.scroll_bottom);
                }
            }
            _ => {}
        }
    }

    fn reset_attrs(&mut self) {
        self.fg = Color::Default;
        self.bg = Color::Default;
        self.attrs = CellAttrs::default();
    }

    /// Write a cursor position report: ESC [ row ; col R
    fn write_response_cpr(&mut self, row: usize, col: usize) {
        self.response_buf.push(0x1b);
        self.response_buf.push(b'[');
        self.write_response_num(row);
        self.response_buf.push(b';');
        self.write_response_num(col);
        self.response_buf.push(b'R');
    }

    fn write_response_num(&mut self, mut n: usize) {
        if n == 0 {
            self.response_buf.push(b'0');
            return;
        }
        let mut buf = [0u8; 10];
        let mut i = 0;
        while n > 0 {
            buf[i] = b'0' + (n % 10) as u8;
            n /= 10;
            i += 1;
        }
        for j in (0..i).rev() {
            self.response_buf.push(buf[j]);
        }
    }
}
