// Line discipline (ADR-014)
//
// Handles canonical mode (line editing, echo) and raw mode
// (passthrough) for TTY devices.

extern crate alloc;

use alloc::collections::VecDeque;

/// Line discipline mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LineMode {
    /// Canonical: line-buffered, echo, basic editing (backspace).
    Canonical,
    /// Raw: character-at-a-time, no echo, no editing.
    Raw,
}

/// Terminal size.
#[derive(Debug, Clone, Copy)]
pub struct WinSize {
    pub rows: u16,
    pub cols: u16,
}

impl Default for WinSize {
    fn default() -> Self {
        WinSize { rows: 25, cols: 80 }
    }
}

/// Signal generated by the line discipline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TtySignal {
    Interrupt,  // Ctrl-C → SIGINT
    Quit,       // Ctrl-\ → SIGQUIT
    Suspend,    // Ctrl-Z → SIGTSTP
    Eof,        // Ctrl-D → EOF
}

/// Output from line discipline processing.
pub enum LdiscOutput {
    /// Single byte to echo back to the terminal.
    Echo(u8),
    /// Multiple bytes to echo back (e.g. BS-SP-BS for erase).
    EchoSeq([u8; 4], u8),
    /// A complete line is ready to be read by the slave.
    LineReady,
    /// A signal was generated.
    Signal(TtySignal),
    /// Byte passes through (raw mode or cooked output).
    Passthrough(u8),
    /// Nothing to do.
    None,
}

/// The line discipline state.
pub struct LineDiscipline {
    mode: LineMode,
    /// Input buffer (canonical mode line editing).
    input_buf: VecDeque<u8>,
    /// Completed lines ready for read.
    cooked_buf: VecDeque<u8>,
    /// Echo enabled.
    echo: bool,
    /// Special characters.
    erase_char: u8,   // backspace
    intr_char: u8,    // Ctrl-C
    quit_char: u8,    // Ctrl-backslash
    susp_char: u8,    // Ctrl-Z
    eof_char: u8,     // Ctrl-D
}

impl LineDiscipline {
    pub fn new() -> Self {
        LineDiscipline {
            mode: LineMode::Canonical,
            input_buf: VecDeque::new(),
            cooked_buf: VecDeque::new(),
            echo: true,
            erase_char: 0x7F,  // DEL
            intr_char: 0x03,   // ETX (Ctrl-C)
            quit_char: 0x1C,   // FS (Ctrl-\)
            susp_char: 0x1A,   // SUB (Ctrl-Z)
            eof_char: 0x04,    // EOT (Ctrl-D)
        }
    }

    pub fn mode(&self) -> LineMode {
        self.mode
    }

    pub fn set_mode(&mut self, mode: LineMode) {
        self.mode = mode;
        if mode == LineMode::Raw {
            // Flush input buffer to cooked buffer in raw mode switch
            while let Some(b) = self.input_buf.pop_front() {
                self.cooked_buf.push_back(b);
            }
        }
    }

    pub fn set_echo(&mut self, echo: bool) {
        self.echo = echo;
    }

    /// Process one byte from the terminal (master side input).
    /// Returns what the line discipline wants to do.
    pub fn process_input(&mut self, byte: u8) -> LdiscOutput {
        match self.mode {
            LineMode::Raw => LdiscOutput::Passthrough(byte),
            LineMode::Canonical => self.process_canonical(byte),
        }
    }

    fn process_canonical(&mut self, byte: u8) -> LdiscOutput {
        // Check signal characters first
        if byte == self.intr_char {
            self.input_buf.clear();
            return LdiscOutput::Signal(TtySignal::Interrupt);
        }
        if byte == self.quit_char {
            self.input_buf.clear();
            return LdiscOutput::Signal(TtySignal::Quit);
        }
        if byte == self.susp_char {
            return LdiscOutput::Signal(TtySignal::Suspend);
        }
        if byte == self.eof_char {
            // EOF: make whatever is in the buffer available
            while let Some(b) = self.input_buf.pop_front() {
                self.cooked_buf.push_back(b);
            }
            return LdiscOutput::Signal(TtySignal::Eof);
        }

        // Erase character (backspace)
        if byte == self.erase_char || byte == 0x08 {
            if self.input_buf.pop_back().is_some() && self.echo {
                // Echoing backspace: BS SP BS to visually erase character
                return LdiscOutput::EchoSeq([0x08, 0x20, 0x08, 0], 3);
            }
            return LdiscOutput::None;
        }

        // Newline — submit line
        if byte == b'\n' || byte == b'\r' {
            while let Some(b) = self.input_buf.pop_front() {
                self.cooked_buf.push_back(b);
            }
            self.cooked_buf.push_back(b'\n');
            if self.echo {
                return LdiscOutput::Echo(b'\n');
            }
            return LdiscOutput::LineReady;
        }

        // Regular character
        self.input_buf.push_back(byte);
        if self.echo {
            LdiscOutput::Echo(byte)
        } else {
            LdiscOutput::None
        }
    }

    /// Read cooked data (slave side).
    /// Returns number of bytes read.
    pub fn read(&mut self, buf: &mut [u8]) -> usize {
        let mut count = 0;
        while count < buf.len() {
            if let Some(b) = self.cooked_buf.pop_front() {
                buf[count] = b;
                count += 1;
                // In canonical mode, stop at newline
                if self.mode == LineMode::Canonical && b == b'\n' {
                    break;
                }
            } else {
                break;
            }
        }
        count
    }

    /// Check if data is available for reading.
    pub fn has_data(&self) -> bool {
        !self.cooked_buf.is_empty()
    }

    /// Bytes available to read.
    pub fn available(&self) -> usize {
        self.cooked_buf.len()
    }
}
